### PR TITLE
Rust-clippy analyzing workflow sample

### PR DESCRIPTION
**Pull request by yongyan-gh**

### CODE REVIEW

**Comment by yongyan-gh** [comment]
@josepalafox pls take a look at the workflow created to analyze repo using rust-clippy and upload SARIF results. Its working fine and i am able to see the issue detected by rust-clippy in security tab. 

Do we need the official Github workflow? It requires Rust official Github action to be created first right? What do you think?

cc @eddynaka @michaelcfanning

**Comment by josepalafox** [comment]
Can you add @leftrightleft and @geekmasher to the test repo, they can help with the code reviews.

**Comment by GeekMasher** [comment]
@yongyan-gh Looks great. I see the results in Code Scanning UI and the workflow looks great.

**Comment by josepalafox** [comment]
Is it using this action?

I understand this is the official one. https://github.com/actions-rs/clippy-check

If so I think we have everything we need to make a starter workflow and then get the integration in the GitHub UI with a starter workflow.

**Comment by yongyan-gh** [comment]
@GeekMasher thanks for checking.

@josepalafox thanks for sharing the official action link. This workflow does not use this action. I created test workflow use the official clippy-check action, tried to generate SARIF output but seems did not work.

Clippy itself does not generate SARIF result, it can be done by other rust crates to convert the clippy json output to a SARIF file by redirecting/piping. e.g.
>/home/runner/.cargo/bin/cargo clippy --message-format=json --all-features --message-format=json `| clippy-sarif | tee results.sarif | sarif-fmt`

Clippy-check action seems does not support piping in input argument. I tried this in the workflow
```
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features | clippy-sarif | tee results.sarif | sarif-fmt
```
And got error:
```
  /home/runner/.cargo/bin/cargo clippy --message-format=json --all-features | clippy-sarif | tee results.sarif | sarif-fmt
  error: Found argument '|' which wasn't expected, or isn't valid in this context
```

Will report the issue to them, once it supports SARIF output we can create the starter workflow.

**Pull request merged**
